### ISSUE TITLE
ability to delete older cert if 2 exist

### ISSUE THREAD

**Issue by doapp-ryanp** [fastlane/pem#59]
I know one of the philosophies of fastlane is to not expose destructive actions, however I think the proposed new feature below is not really destructive but more of a replace.  

I would like a sub command of `PEM` (ex: `--remove-oldest`) to do the following:

If 2 valid [production] push certificates exist, remove the oldest of the 2

While this command does delete an asset, it only does so if there is a valid asset already in its place.  The reason for wanting this feature, is pruning 2 certs down to one manually before running `PEM [--force]` does not scale.  When you have many apps in many different teams it is extremely time consuming to find dupe bundle IDs and delete the oldest. When this spans multiple teams it gets even more time consuming.

Example:
`PEM -u "memberctr@myco.com" -a "myapp.bundle.id" -t "MYTEAMID" --remove-oldest`

**Comment by KrauseFx** [comment]
Hey @doapp-ryanp, that makes perfect sense in my opinion. It's true that I try to avoid implementing any destructive actions, but your argumentation sounds reasonable. `PEM` as it is now still uses web-scraping but will soon be upgraded to use [spaceship](https://spaceship.airforce), resulting in a much faster and more stable tool. 

I can't promise any ETA though.

**Comment by doapp-ryanp** [comment]
Sounds good.

I'm not that great with Ruby (nor a fan honestly) otherwise I'd offer to do the PEM spaceship upgrade

**Comment by doapp-ryanp** [comment]
Now that PEM is using spaceship under the covers, is this feature request more feasible to pull off?

**Comment by KrauseFx** [comment]
Yeah, tagged as feature :+1:

**Comment by Sega-Zero** [comment]
any ETA on this or is it still unknown?

**Comment by KrauseFx** [comment]
@Sega-Zero Sorry, we're currently not working on this. However feel free to take a look at [countdown](https://github.com/fastlane/countdown) to get started with contributing to `fastlane` :+1:
