### ISSUE TITLE
Integrate into Match ? 

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/pem#85]
Would be great to have this in the repo as well :)

**Comment by KrauseFx** [comment]
What would you want to store? pem files? p12 files?

**Comment by jcampbell05** [comment]
Mainly the cer and p12. The pen could be genrated from those two things.and match already handles cer and p12

**Comment by fantattitude** [comment]
Yeah that's something I'd find useful too, you never know when you'll need them again.

**Comment by KrauseFx** [comment]
@fantattitude I don't think you'll ever need them again. You can always just revoke certs and generate new ones.

**Comment by jcampbell05** [comment]
For me it's just being able to easily commit them to the git repo. And have them in the same place so people such as the server team can find it.
