### ISSUE TITLE
missing team id in non interactive mode still blocks

### ISSUE THREAD

**Issue by doapp-ryanp** [fastlane/PEM#96]
Commenting for https://github.com/fastlane-old/pem/issues/76 is locked so started a new issue here.

Running PEM 2.26.0 in a jenkins non-interactive environment.  The issue above was to request a new feature that allowed a non-interactive program to detect when team ID is not found, and to take corrective action.

I just ran into the problem in v2.26.0:

```
INFO [2017-05-11 14:56:53.68]: Starting login with user 'me@me.com'
Couldn't find team with ID 'XXXXXXXXXX'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
...
```
PEM then blocks my program as it is waiting for input.

I would like PEM to blow up in this scenario and have a return code so that I can take corrective action.  Any idea why https://github.com/fastlane-old/fastlane_core/commit/a5f24e46cc2168c46a9051c3b522663e01fc0ace to address this didn't work?

**Comment by KrauseFx** [comment]
Hey @doapp-ryanp, please submit this issue again on the main repo of _fastlane_ 👍

**Comment by KrauseFx** [comment]
The reason why this doesn't work yet is that spaceship doesn't have access to fastlane_core. However that's something we want to fix. Please submit an issue so we can track it
